name: jawara_kelompok3
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0

  # Utilities
  http: ^1.1.0
<<<<<<< HEAD
  file_picker: ^8.1.3

  # Firebase (VERSI COCOK)
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.4.10

  # PDF
  pdf: ^3.11.0
  printing: ^5.11.0
  flutter_pdfview: ^1.0.0
=======
  pdf: ^3.11.0
  printing: ^5.11.0
  flutter_pdfview: ^1.0.0   
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: 13.0.4
>>>>>>> 89235790c9b093f032543b6e0082f64794564526

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
