name: jawara_kelompok3
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0

  # Utilities
  http: ^1.1.0
  file_picker: ^8.1.3

  # Firebase (VERSI COCOK)
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.4.10

  # PDF
  pdf: ^3.11.0
  flutter_pdfview: ^1.0.0
  path_provider: ^2.0.9
  printing: ^5.13.1
  open_file: ^3.3.2

  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.1.8

  # Launcher Icon
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
